Repository Tulga1aa/e-parking-new, pull requests merged in 2025-06, with the labels that each got.

#1 Footer-contact-zurag-fix
  app/layout.tsx
  app/page.tsx
  components/contact.tsx
  components/features-section.tsx
  components/header.tsx
  components/hero-section.tsx
  public/images/Parking-spot.png
  public/images/parking-map.png
Labels: bug, enhancement

#2 picture-contact
  app/contact/page.tsx
  app/page.tsx
  components/header.tsx
  components/hero-section.tsx
  package-lock.json
  package.json
  public/images/Parking-spot.png
  public/images/features-illustration.png
  public/images/parking-map.png
Labels: documentation

#3 Location
  app/contact/page.tsx
  app/page.tsx
  components/LocationMap.tsx
  components/hero-section.tsx
  components/location-section.tsx
  public/images/parking-map.png
Labels: enhancement

#4 bug fixed
  app/layout.tsx
  components/LocationMap.tsx
  components/header.tsx
  components/location-section.tsx
  package-lock.json
  package.json
Labels: bug
